version: "2"

services: 
  masterdb:
    build : master
    container_name: masterdb
    ports : 
       - 3308:3306 

  slavedb:
    build : slave
    container_name : slavedb
    links:
      - masterdb
    ports : 
       - 3307:3306 
  
  drupal:
    build : website-drupal
    container_name : drupal
    links : 
         - masterdb
         
    ports : 
       - 8001:80  

